#!/bin/bash

function print_help {
    echo "Usage: ./blog <command> [OPTION]...
    new <title>                         Create a new blog post
    build                               Builds the blog
    serve                               Starts a local server
    "
}

# Spin up a super simple dev server.
function spin_up_dev_server {
    cd build
    python3 -m http.server 8000
}

# Generate new blog posts or hot take.
function new {
    if [[ ! $1 ]]; then
        echo "Please specify a title."
        print_help
        exit 1
    fi

    title=$1
    date=$(date +"%Y-%m-%d")
    filename="$(date +"%Y%m%d")_$(echo "$1" | tr '[:upper:]' '[:lower:]' | sed s/\ /_/g).md"
    filepath="docs/blog/$filename"

    frontmatter="---\n"
    frontmatter+="title: $title\n"
    frontmatter+="created: $date\n"
    frontmatter+="show_social_links: true\n"
    frontmatter+="tags: []\n"
    frontmatter+="---\n"

    echo -e "$frontmatter" > "$filepath"

    code "$filepath"
}


case $1 in
    build)
        ./build.sh
        ;;
    serve)
        spin_up_dev_server
        ;;
    help)
        print_help
        ;;
    new)
        new "$2" "$3" "$4"
        ;;
    *)
        print_help
        ;;
esac
